package payment

import (
	"strings"
	"testing"

	"github.com/Wei-Shaw/sub2api/internal/config"
)

func TestProvideEncryptionKeySkipsAutoGeneratedTotpKey(t *testing.T) {
	t.Parallel()

	cfg := &config.Config{
		Totp: config.TotpConfig{
			EncryptionKey:           strings.Repeat("a", 64),
			EncryptionKeyConfigured: false,
		},
	}

	key, err := ProvideEncryptionKey(cfg)
	if err != nil {
		t.Fatalf("ProvideEncryptionKey returned error: %v", err)
	}
	if len(key) != 0 {
		t.Fatalf("encryption key len = %d, want 0", len(key))
	}
}

func TestProvideEncryptionKeyUsesConfiguredTotpKey(t *testing.T) {
	t.Parallel()

	cfg := &config.Config{
		Totp: config.TotpConfig{
			EncryptionKey:           "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
			EncryptionKeyConfigured: true,
		},
	}

	key, err := ProvideEncryptionKey(cfg)
	if err != nil {
		t.Fatalf("ProvideEncryptionKey returned error: %v", err)
	}
	if len(key) != 32 {
		t.Fatalf("encryption key len = %d, want 32", len(key))
	}
}

func TestProvideEncryptionKeyRejectsConfiguredInvalidLength(t *testing.T) {
	t.Parallel()

	cfg := &config.Config{
		Totp: config.TotpConfig{
			EncryptionKey:           "abcd",
			EncryptionKeyConfigured: true,
		},
	}

	_, err := ProvideEncryptionKey(cfg)
	if err == nil {
		t.Fatal("expected error for invalid key length")
	}
}

func TestProvidePreviousEncryptionKeysFollowsPrimaryConfiguration(t *testing.T) {
	t.Parallel()

	previous := "fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210"
	cfg := &config.Config{
		Totp: config.TotpConfig{
			EncryptionKey:           "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
			EncryptionKeyPrevious:   previous + ", ",
			EncryptionKeyConfigured: true,
		},
	}
	keys, err := ProvidePreviousEncryptionKeys(cfg)
	if err != nil {
		t.Fatalf("ProvidePreviousEncryptionKeys returned error: %v", err)
	}
	if len(keys) != 1 || len(keys[0]) != 32 {
		t.Fatalf("previous keys = %d entries, want 1 x 32 bytes", len(keys))
	}

	// 主密钥是自动生成的：历史密钥同样不提供，和 ProvideEncryptionKey 一致。
	cfg.Totp.EncryptionKeyConfigured = false
	keys, err = ProvidePreviousEncryptionKeys(cfg)
	if err != nil || len(keys) != 0 {
		t.Fatalf("auto-generated primary must yield no previous keys, got %d keys, err=%v", len(keys), err)
	}

	// 历史密钥与主密钥重复是配置错误：两个 provider 都报错。
	cfg.Totp.EncryptionKeyConfigured = true
	cfg.Totp.EncryptionKeyPrevious = cfg.Totp.EncryptionKey
	if _, err := ProvidePreviousEncryptionKeys(cfg); err == nil {
		t.Fatal("expected error for previous key duplicating the primary")
	}
	if _, err := ProvideEncryptionKey(cfg); err == nil {
		t.Fatal("expected error for previous key duplicating the primary")
	}
}
